### ISSUE TITLE
Is there possibility to change value for helping bike during walking?

### ISSUE THREAD

**Issue by Hadatko** [andrey-pr/OpenBafangTool#17]
Bike walking support is really slow and i would like to double it. Is there parameter for it? I couldn't find info related to that.

**Comment by andrey-pr** [comment]
Its not supported in release, but added in one of dev branches. I just have to test it and add to new release

**Comment by Hadatko** [comment]
Great work. Thank you

**Comment by andrey-pr** [comment]
Hello. I published new release with parameter for walk mode speed

**Comment by Hadatko** [comment]
Thank you for letting me know. I will try soon.

**Comment by Hadatko** [comment]
Hi, i tested latest app. Even though it looks like it wrote parameters correctly into engine, the behavior is as before. When i read data i have the values i set. I didn't see option for walking assistant so i changed size of wheels from 29" to 14" and that doesn't have any impact for walking assistantce. After change i still see in display from bike that wheel size is 29"

**Comment by Hadatko** [comment]
Then i likely set 16" not 14"

**Comment by andrey-pr** [comment]
> Then i likely set 16" not 14"
> 

Please show me screenshot

**Comment by Hadatko** [comment]
Hmm not possible right now. But it doesn't matter as behavior didn't change and set request passed all green

**Comment by Hadatko** [comment]
FYI: Today i was on bike. It looks the calculation staied with my original wheel size, but it was helping me whole time even i crossed the speed limit. Although i wanted achieve something else, today it helped me as i was lacking in time.
